import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {  SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "./sidebar/AppSideBar";
import Search from "./sidebar/SeachItem";
import SearchItem from "./sidebar/SeachItem";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <AppSideBar />
          <main className="w-full">
            <div className="p-4 justify-between flex border-b bg-white sticky top-0 z-10">
              <SidebarTrigger className="hover:bg-gray-100 " />
             <div>
               <SearchItem/>
             </div>
            </div>
            <div>
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
