import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "./sidebar/AppSideBar";
import Search from "./sidebar/SeachItem";
import SearchItem from "./sidebar/SeachItem";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <AppSideBar />
          <main className="w-full">
            <div className="p-4 justify-between flex border-b bg-white sticky top-0 z-10">
              <SidebarTrigger className="hover:bg-gray-100 " />
              <div>
                <SearchItem />
              </div>
            </div>

            <div className="relative min-h-[calc(100vh-64px)]">
              <div className="pb-20">
                {children}
              </div>


              {/* Footer */}
              <div className="absolute  bottom-0 left-0 right-0 flex items-center justify-center p-10 text-sm text-muted-foreground">
                <div className="flex items-center gap-5">
                  <span>Smart Queue System © 2026 smart queue, Inc.</span>
                  <span className="h-4 w-px bg-gray-300" />
                  <span>Community guidelines · Terms of service</span>
                </div>
              </div>
            </div>
          </main>

        </SidebarProvider>

      </body>
    </html>
  );
}
